apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-books
  labels: 
    app: {{ .Release.Name }}-{{ .Chart.Name }}-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-books
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-books
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-books
        image: {{ .Values.image.books.repository }}:{{ .Values.image.books.tag }}
        imagePullPolicy: Always
        ports:
        - name: ebooksapi-port
          containerPort: 9000
        env:
         - name: MONGOURI
           value: 'mongodb://emongo:27017/epoc'
         - name: SECRETORKEY
           valueFrom:
             secretKeyRef:
               name: {{ .Release.Name }}-{{ .Chart.Name }}-appsecret
               key: jwt-secret
         - name: DB_USERNAME
           value: 'root'
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: {{ .Release.Name }}-kkartcharts-database-dbsecret
               key: mysqldb-pass
      imagePullSecrets:
      - name: regcred 
     
