apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-main
  labels: 
    app: {{ .Release.Name }}-{{ .Chart.Name }}-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-main
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-main
        image: {{ .Values.image.main.repository }}:{{ .Values.image.main.tag }}
        imagePullPolicy: Always
        ports:
        - name: enodeapi-port
          containerPort: 5000
        env:
         - name: MONGO_URI
           value: 'mongodb://emongo:27017/epoc'
         - name: JWT_SECRET
           valueFrom:
             secretKeyRef:
               name: {{ .Release.Name }}-{{ .Chart.Name }}-appsecret
               key: jwt-secret
      imagePullSecrets:
      - name: regcred
     
